import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/context/theme/ThemeProvider";
import { cn } from "@/lib/utils";
import GloabalContextProvider from "@/context/globalContext/GlobalContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
      <ThemeProvider>
        <GloabalContextProvider>
          {children}
        </GloabalContextProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
